### ISSUE TITLE
Cmake is Win specific

### ISSUE THREAD

**Issue by zarquon42b** [morphomuseum/MorphoDig#3]
On Linux, compilation does not work and cmake contains some content that is win only.

**Comment by zarquon42b** [comment]
Just wanted you to know that I found the time to work on this an compiled it successfully on Linux. I will commit necessary changes and update the README as soon as I find the time.

**Comment by renaud-lebrun** [comment]
@zarquon42b 
Dear Stefan, 
it works thank you so much! (and all my apologies for answering so late, I am on holiday).

I just merged my last changes into the Linux_hacks branch. Could you please verify that it still works on your side so that we can merge "Linux_hacks" inside the master branch ?

Thanks again and have a nice end of holiday if you are still out of your lab,
Best regards,
Renaud.

**Comment by zarquon42b** [comment]
Hi Ronan,
everything works fine, you can merge it.
All the best
Stefan
